### PR TITLE
Fix not enough arguments in call to odhdeploy.ApplyParams

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Fix PR for https://github.com/opendatahub-io/opendatahub-operator/pull/2248

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]

**Comment by zdtsw** [comment]
caused by https://github.com/opendatahub-io/opendatahub-operator/pull/2248 gets merged into main first, https://github.com/opendatahub-io/opendatahub-operator/pull/2233 was merged later

**Comment by zdtsw** [comment]
PR no need sync to RHDS, it has been included in https://github.com/opendatahub-io/opendatahub-operator/pull/2264
